"""LLM Provider Abstraction Layer.

Decouples the system from specific model backends (Local HuggingFace, Ollama, vLLM, or Mock).
Supports Qwen 2.5/3 14B primary, Llama 3.1 8B fallback, and Mock mode for development without GPU.
"""

from abc import ABC, abstractmethod
from typing import Optional, Dict, Any
from pydantic import BaseModel
from backend.config.settings import settings


class LLMRequest(BaseModel):
    prompt: str
    system_prompt: Optional[str] = (
        "You are DeadlockTutorLLM, a specialized OS deadlock tutor. "
        "Teach step-by-step, maintain syllabus grounding, explain misconceptions clearly, "
        "and never hallucinate calculations."
    )
    temperature: float = 0.2
    max_tokens: int = 1024


class LLMResponse(BaseModel):
    content: str
    model_name: str
    metadata: Dict[str, Any] = {}


class BaseLLMProvider(ABC):
    """Abstract interface for LLM inference."""

    @abstractmethod
    def generate(self, request: LLMRequest) -> LLMResponse:
        pass


class MockLLMProvider(BaseLLMProvider):
    """Mock LLM Provider for rapid development and testing without GPU."""

    def __init__(self, model_name: str = "mock-tutor-v1"):
        self.model_name = model_name

    def generate(self, request: LLMRequest) -> LLMResponse:
        prompt_snippet = request.prompt[:80].strip()
        response_text = (
            f"**[DeadlockTutorLLM Development Mode - Model: {self.model_name}]**\n\n"
            f"Received query context regarding: '{prompt_snippet}...'\n\n"
            "Here is the educational breakdown:\n"
            "1. **Core Concept**: Deadlock occurs when a set of processes are blocked because each process is holding a resource and waiting for another resource acquired by some other process.\n"
            "2. **Coffman Conditions**: Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait.\n"
            "3. **Key Distinction**: An UNSAFE state does NOT strictly mean the system is currently deadlocked. An unsafe state means no safe sequence is guaranteed to prevent future deadlock if all processes request their maximum claim.\n\n"
            "*(This response was generated by the mock LLM provider for Phase 1 MVP validation.)*"
        )
        return LLMResponse(
            content=response_text,
            model_name=self.model_name,
            metadata={"provider": "mock", "tokens": 150}
        )


def get_llm_provider() -> BaseLLMProvider:
    """Factory to retrieve configured LLM provider."""
    provider_type = settings.llm_provider.lower()
    if provider_type == "mock":
        return MockLLMProvider(model_name=settings.primary_model)
    # Additional providers (Ollama, HuggingFace Local, vLLM) can be wired here in Phase 4
    return MockLLMProvider(model_name=settings.primary_model)
